language: php

php:
  # aliased to a recent 5.5.x version
  - 5.5
  # aliased to a recent 5.6.x version
  - 5.6
  # aliased to a recent 7.x version
  - 7.0

# optionally specify a list of environments, for example to test different RDBMS
env:
  - SYMFONY_ENV=test

# omitting "script:" will default to phpunit
# use the $SYMFONY_ENV env variable to determine the phpunit.xml to use
#script: phpunit --configuration phpunit_$SYMFONY_ENV.xml --coverage-text
script:
  - composer install
  - php app/console doctrine:schema:update --force
  - phpunit -c app

