app:
    resource: "@AppBundle/Controller/"
    type:     annotation

UserBundle:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /

AppBundle:
    resource: "@AppBundle/Resources/config/routing.yml"
    prefix: /
