user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /

room:
    resource: "@AppBundle/Resources/config/routing.yml"
    prefix:   /room

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

homepage:
    path:   /
    defaults:  { _controller: AppBundle:Default:index}
