parameters:
#    parameter_name: value


services:
    UserService:
        class:     UserBundle\Entity\UserService
        arguments: [ @doctrine.orm.entity_manager ]

    RoomService:
        class: AppBundle\Service\RoomService
        arguments: [ @doctrine.orm.entity_manager ]

