# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:

services:

    AnalyticsService:
        class: AppBundle\Service\AnalyticsService
        arguments: [ @doctrine.orm.entity_manager ]
